Added runekit plugin
runelite/plugin-hub pull request #1596
Opened 2021-06-27 00:09 UTC by ImToxicCode

This plugin sends http post requests to the runekit api when a user has planted a crop or built a birdhouse.

2021-06-29 00:13 UTC, Nightfirecat commented
Your plugin entry must have a `warning` defined as it submits data to an external site. Example: https://github.com/runelite/plugin-hub/blob/master/plugins/shared-implings#L3

2021-06-29 02:14 UTC, ImToxicCode commented
Sorry about commit b17da0 that was a mistake.

2021-07-02 13:22 UTC, ImToxicCode commented
Is there anything else I need to add to the plugin before it can merge? 

Thank you

2021-07-06 20:24 UTC, raiyni requested changes

2021-07-06 20:24 UTC, raiyni commented on plugins/runekit
> +disabled=true
remove

2021-07-06 21:05 UTC, ImToxicCode reviewed
Removed disabled field

2021-07-12 13:36 UTC, raiyni commented
Do not commit that .idea directory.

2021-07-12 15:09 UTC, ImToxicCode commented
@raiyni What should I do?

2021-07-12 15:13 UTC, Nightfirecat commented
Remove these files from this PR:
* .idea/.gitignore
* .idea/modules.xml
* .idea/plugin-hub.iml
* .idea/vcs.xml

2021-07-12 19:06 UTC, ImToxicCode commented
Did I do this incorrectly ?

2021-07-12 19:19 UTC, Nightfirecat commented
Yes, that looks better.

2021-07-12 20:04 UTC, Nightfirecat commented
[`client.getVarbitValue()` must be called on the client thread.](https://github.com/ImToxicCode/runekit/blob/3f57448109482d4e48cbbc62ffabaa04e701981e/src/main/java/com/runekit/services/FarmingService.java#L154) This method is run on EDT when config is changed. Please utilize `ClientThread` to address this. (you should run your plugin with `-ea` for assertions to trip during development)

2021-07-13 05:09 UTC, merged