Add npc-collection-log plugin
runelite/plugin-hub pull request #3837
Opened 2023-01-28 00:19 UTC by ElOsoGroso

NPC Collection Log

This plugin shows a panel when you initiate combat with any NPC, showing information about which items are possible to receive from them, and which ones you've already got in your collection log, or in your bank.

2023-02-10 03:42 UTC, raiyni commented
Would be helpful if you scaled down the icon size.

2023-02-10 17:10 UTC, ElOsoGroso commented
> Would be helpful if you scaled down the icon size.

The nav-icon.png in resources or icon.png? I assume the nav-icon one. Yeah I can do that.

2023-02-10 18:07 UTC, ElOsoGroso commented
> Would be helpful if you scaled down the icon size.

That's been resized.

2023-02-26 03:29 UTC, Nightfirecat requested changes

2023-02-26 03:29 UTC, Nightfirecat commented on plugins/npc-collection-log
> +
```suggestion
warning=This plugin submits your account hash and IP address to a server not controlled or verified by the RuneLite developers.
```

2023-02-28 03:56 UTC, merged

2023-02-28 05:36 UTC, ElOsoGroso commented
After this merge... it seems to be immediately crashing upon login or installing the plugin. Locally I don't see the same behavior at all @Nightfirecat