Add citizens plugin
runelite/plugin-hub pull request #4813
Opened 2023-08-28 20:53 UTC by gc

Repo: https://github.com/gc/citizens
Description: Adds 'fake NPCs' (Citizens for clarity) around the world, which walk/talk/animate. 

If you are loading the plugin into your client to run it locally, you will find the most citizens in varrock.
They despawn when they are too far away from the player (25~ tiles distance from the player).

2023-08-28 20:57 UTC, raiyni requested changes

2023-08-28 20:57 UTC, raiyni commented on plugins/citizens
> +repository=https://github.com/gc/citizens
```suggestion
repository=https://github.com/gc/citizens.git
```

2023-08-28 20:59 UTC, gc commented on plugins/citizens
> +repository=https://github.com/gc/citizens
@raiyni Oops sorry. Fixed.

2023-08-28 21:24 UTC, gc commented
Fixed the error relating to the gson usage by using the injected gson instance.

2023-10-02 22:55 UTC, Nightfirecat commented
Have you tried running this plugin outside of your development environment? [It looks like it's trying to load files from your filesystem rather than from the plugin's resources](https://github.com/gc/citizens/blob/187271ee3523039f33bb0b83a6c150fb4107c757/src/main/java/com/magnaboy/scripting/ScriptLoader.java#L10), which would not work for other users. (This same problem seems to exist in Util.java and CitizenRegion.java)
I know the panel is only added for development [but you add it here and don't ever remove it, even on plugin shutdown](https://github.com/gc/citizens/blob/187271ee3523039f33bb0b83a6c150fb4107c757/src/main/java/com/magnaboy/CitizensPlugin.java#L91). Please fix that so there's no chance it ends up being an issue later on when it comes out of development.
Code generally LGTM otherwise.

2023-10-10 22:40 UTC, Nightfirecat commented
Your shutDown code is adding the nav button a second time, not removing it. Please test this by toggling your plugin off then back on after starting your client.

2023-10-11 01:57 UTC, gc commented
Apologies for that, not sure how I messed that up. I fixed that, and tested it making sure it gets removed when turning off the plugin. (and that it doesnt appear at all unless in development).

2023-10-11 04:57 UTC, merged