Create Ent-trimmer v1.0.0
runelite/plugin-hub pull request #6144
Opened 2024-06-08 22:18 UTC by pwatts6060

2024-07-19 10:28 UTC, aHooder commented
Closing & re-opening to re-run the checks.

2024-07-19 10:40 UTC, aHooder requested changes
You need to synchronize the `ImageIO.write` call at https://github.com/pwatts6060/runelite-plugins/blob/81a327c542c807336993c291730154fd88f22dc5/src/main/java/com/ent/discord/DiscordWebhook.java#L113 to appease the checker, like so:
```java
synchronized (ImageIO.class)
{
	ImageIO.write(bufferedImage, "png", byteArrayOutputStream);
}
```
LGTM otherwise

2024-08-04 16:13 UTC, aHooder approved these changes

2024-08-04 16:18 UTC, aHooder commented
Your PR will have to wait for a maintainer to review it, due to the HTTP request, but this looks alright to me now. For some reason, it's still warning about ImageIO synchronization though :thinking: Presumably it's unable to check for the synchronization block.

2024-08-16 00:00 UTC, Nightfirecat approved these changes

2024-08-16 00:00 UTC, merged