Update Pneck reminder to add necklace of faith
runelite/plugin-hub pull request #6388
Opened 2024-08-02 14:47 UTC by AbusiveTuna

2024-08-02 15:33 UTC, pajlada commented
Your config group right now is `didICompost`, which I assume is not what you want

2024-08-03 19:57 UTC, TheStonedTurtle requested changes
You must update the config group from `didICompost` to a value unique to this plugin. Config group names can not be shared between plugins.

You should probably also do the change @pajlada mentioned but that is not required.

2024-08-05 16:57 UTC, AbusiveTuna commented
> You must update the config group from `didICompost` to a value unique to this plugin (and matches or is at least very closely related to the plugin name). Config group names can not be shared between plugins.
> 
> You should probably also do the change @pajlada mentioned but that is not required.

Oops that was dumb of me, updated config group and changed to use RL's ItemIds

2024-08-05 17:20 UTC, iProdigy approved these changes

2024-08-05 17:29 UTC, TheStonedTurtle approved these changes

2024-08-05 17:30 UTC, merged