Add Twitch Live Loadout Plugin
runelite/plugin-hub pull request #684
Opened 2020-10-18 19:50 UTC by pepijnverburg

This plugin allows the RuneLite client to synchronize game data to the Twitch Extension API (https://dev.twitch.tv/extensions) and give stream viewers live interfaces to interact. Currently inventory items, equipment items, bank items, skill levels and basic combat statistics are synchronized. 

It is built in such a way that any Twitch Extension can work with this (this is configurable via the plugin settings). The accompanied Twitch Extension is currently being reviewed by Twitch as well and is made completely in the style of the native game client (see screenshots in README).

Let me know if you have suggestions for improvements or would like to see a live stream with the plugin and Twitch extension in action. That is no problem to arrange (also doing the same with the Twitch reviewing team).

2020-10-18 19:52 UTC, dekvall commented on plugins/twitch-live-loadout
> +repository=https://github.com/pepijnverburg/osrs-runelite-twitch-live-loadout-plugin
```suggestion
repository=https://github.com/pepijnverburg/osrs-runelite-twitch-live-loadout-plugin.git
```

2020-10-28 13:32 UTC, abextm requested changes
Your support url is not a url

2020-10-28 13:36 UTC, pepijnverburg commented
You mean the `support` property in https://github.com/pepijnverburg/osrs-runelite-twitch-live-loadout-plugin/blob/ffe082ebb7f87bde83204620ca6fb934d2ce6518/runelite-plugin.properties#L3? Was expecting a way of contacting the maintainer there. I'll change it to the Github page.

2020-10-28 14:04 UTC, abextm commented
your build is still failing

2020-10-28 17:06 UTC, merged